#! /usr/bin/env python3

# author: Eric Dumas
# email: edumas000@gmail.com
# description: run GRAV CMS from Terminal.

import os
import subprocess
from os import path

sys_router_file = path.exists('./system/router.php') #Checks to see if a file in the current directory exist in order for GRAV CMS to RUN a Webserver.
index_file = path.exists('./index.php') #Checks to see if a file in the current directory exist in order for GRAV CMS to RUN a Webserver.

def _grav():
    if sys_router_file and index_file:
        print('I will start GRAV CMS now!')
        port_number = int(input('What Port would you like to run GRAV CMS on? (8000, 8888, etc) '))
        subprocess.run('php -S localhost:{} system/router.php'.format(port_number), shell=True)
    else:
        print('It seem you might be in the wrong directory.... please check back and Try Again :)')

if __name__ == '__main__':
    _grav()